apiVersion: v1
kind: Service
metadata:
  name: game-searcher-service
  namespace: default
spec:
  selector:
    app: game-searcher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
