name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: 'movsho/game-searcher'
      DOCKER_HELM: 'movsho/game-searcher-helm'
      GIT_BRANCH: 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Extract version from file
        id: extract_version
        run: |
          VERSION=$(cat VERSION.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -f ./Dockerfile -t $DOCKER_IMAGE:${{ env.VERSION }} .
          echo 'Docker image built successfully'

      - name: Push Docker image
        run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker push $DOCKER_IMAGE:${{ env.VERSION }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Build and push Helm chart
        run: |
          helm package helm
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          helm push game-searcher-helm-${{ env.VERSION }}.tgz oci://registry-1.docker.io/movsho/

  env:
    MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
    MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
    MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
    MONGO_DB_USER: ${{ secrets.MONGO_DB_USER }}
    MONGO_DB_PASS: ${{ secrets.MONGO_DB_PASS }}
