name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: 'movsho/game-searcher'
      DOCKER_HELM: 'oci://registry-1.docker.io/movsho/game-searcher-helm'
      GIT_BRANCH: 'main'
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
      MONGO_DB_USER: ${{ secrets.MONGO_DB_USER }}
      MONGO_DB_PASS: ${{ secrets.MONGO_DB_PASS }}
      MONGO_HOST: ${{ secrets.MONGO_HOST }}
      MONGO_PORT: ${{ secrets.MONGO_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set version
        id: set_version
        run: echo "VERSION=0.1.0-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -f ./Dockerfile -t ${{ env.DOCKER_IMAGE }}:${{ steps.set_version.outputs.VERSION }} .

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_IMAGE }}:${{ steps.set_version.outputs.VERSION }}

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Replace version in Chart.yaml
        run: sed -i 's/PLACEHOLDER_VERSION/${{ steps.set_version.outputs.VERSION }}/' helm/Chart.yaml

      - name: Log in to Helm OCI registry
        run: helm registry login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }} registry-1.docker.io

      - name: Build and push Helm chart
        run: |
          helm package helm
          ls -al game-searcher-helm-0.1.0-${{ steps.set_version.outputs.VERSION }}.tgz
          helm push game-searcher-helm-0.1.0-${{ steps.set_version.outputs.VERSION }}.tgz ${{ env.DOCKER_HELM }}
